version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WombletechRHoK"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-23x9qmrn35kq"
s3_prefix = "WombletechRHoK"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
